### ISSUE TITLE
Add throttling

### ISSUE THREAD

**Issue by subzero911** [magnuswikhog/easy_debounce#15]
It works right vice versa to debounce.
```dart
EasyDebounce.throttle(
'my-throttle',
Duration(milliseconds: 500),
() => products.search(text),
);
```
If you put this method to the button handler and tap the button, it immediately starts searching, and blocks the button for 500 ms.

**Comment by magnuswikhog** [comment]
I'm not sure I understand how it's supposed to "block the button"? Could you clarify the use case by providing a more complete example?

**Comment by subzero911** [comment]
Please check out https://pub.dev/documentation/rxdart/latest/rx/ThrottleExtensions/throttle.html
Throttle is an opposite operation to debounce. It fires a callback on first event; then ignores all the consequent events for a period of time.

**Comment by JamesMcIntosh** [comment]
Hi @magnuswikhog ,

What Sergey is saying that it is handy in some situations to have the opposite execution behaviour, currently EasyDebounce will execute the event after the timeout has elapsed, what he wants is for the execution to happen immediately and not allow another one to be requested until the timeout has lapsed.

An autocomplete search box is a very good example where you don't want to spam your API while someone is typing but you do want to get results proactively. i.e. An autocomplete with 4 characters threshold for search and a throttle of 1 request per 0.5s.

User inputs 4 characters, trigger search, throttle for 0.5s
User inputs 2 more characters, throttle waits
0.5s elapsed from previous search, new search occurs
User inputs 4 more characters, throttle waits
0.5s elapsed from previous search, new search occurs
...

Kind regards
James

**Comment by JamesMcIntosh** [comment]
There are some other options for throttling already in the ecosystem.
https://pub.dev/packages?q=throttle

After having a quick look at them none have the simple "naming" strategy which you have used to help decouple the function from the debounce. The cleanest looking one I found was [rate_limiter](https://pub.dev/packages/rate_limiter) but it is quite different in that wraps the function.

I had a bit of a think whether this library should even tackle this problem / accept a PR, normally things like debounce and throttle behaviour do go together so it is a good fit. You probably just need to decide if you think that having a separate package may be a better option, i.e. easy_throttle

**Comment by JamesMcIntosh** [comment]
PR #18 adds a throttle implementation for review.

**Comment by magnuswikhog** [comment]
Finally got around to merging this, thanks for your patience and contributions!
