### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by GJJ2019** [magnuswikhog/easy_debounce#5]
This is a request to add support for null safety to package:easy_debounce

**Comment by DarkMikey** [comment]
@magnuswikhog Could you please review & merge? This is the last package that needs to get updated to support sound null safety.

**Comment by GJJ2019** [comment]
I already using #6 in one my application its working fine for me 
u can also try this pull request:
` easy_debounce:`
`   git: https://github.com/GJJ2019/easy_debounce`

**Comment by magnuswikhog** [comment]
Version 2.0.0 migrated to null safety, see commit 6adc3dccd616f641db229d959fe5171d12a4fc33

**Comment by GJJ2019** [comment]
why not add **`required`** keyword ?

**Comment by magnuswikhog** [comment]
@GJJ2019 Not sure what you mean, where do you see any need for using `required`? There are no named parameters without default values - in fact, there are no named parameters at all. Making them named would break previously working code for all existing users of this package, so I don't really see any benefit?

**Comment by GJJ2019** [comment]
u can check #6  PR

**Comment by magnuswikhog** [comment]
I did, and as far as I can tell 99% of it has nothing to do with null safety, but rather with changing the method signature and making all parameters named. Which of course will break working code for all existing users.

The only change needed for null safety was to change the minimum required SDK version.

**Comment by DarkMikey** [comment]
Sorry that I've started this discussion, anyway thanks for changing the minimum required SDK version.
