### ISSUE TITLE
Consider providing an ability to force the debounce callback to fire immediately

### ISSUE THREAD

**Issue by jamesderlin** [magnuswikhog/easy_debounce#7]
Currently if someone is using `EasyDebounce` to update some state but uses `EasyDebounce.cancel`, they either will lose the last state update or they must keep their own reference to the callback so that they can immediately force a final update.

Consider adding a `void force(String tag)` method or modifying `cancel` to take an optional, say, `executeNow` `bool` parameter to allow the pending callback to be fired immediately.

**Comment by magnuswikhog** [comment]
Thanks for the suggestion!

I have just published [version 2.0.1](https://pub.dev/packages/easy_debounce/versions/2.0.1) which has a `fire(String tag)` method for executing a debouncers target function immediately. `fire()` does not cancel or remove the debouncer, so if you want to fire it and cancel it, you would need to call `fire()` first and then `cancel()`.

There's also a new `cancelAll()` method for cancelling all debouncers.
